language: node_js
node_js:
- '0.11'
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
script:
- grunt test --saucelabs
env:
  global:
  - secure: lbskRBYBw8qC8ewCYsaXu6soAJr7zsGVrTptDxyIfnDMSjeKGBI12pPoJSbp4r2ZoA5+QPDR0r1v6O0gBqwtYGxUCjQzw+uNPD1PdGZKRy9sdVXn3ZmeVQlsPan8GQ1ObrX1zNm5P/V+2xNkTnNUstCMvRV0IGGkYFXpvZXAubo=
  - secure: Ywvn7bdtN4t+qskZd5dzQi6Aoq5taeV4EFdbjeiLpoe8Cjyg0xuZKgAAMIbdaE0JE+KnEnxM5w518T96ZC+JwCBgNy7Cq3luUcYbIrD18C4ZhBEaNy6y06DBJ9e3X7oCLTzjUUAPY6aheXADgJcW8804VVkAkhbVkSiFP6YQYQw=
